// Auto-generated Strux type definitions
// Run 'strux types' to regenerate from Go code
// This file is automatically generated. DO NOT EDIT

// Strux Runtime API
// Strux Runtime API
declare namespace StruxRuntime {
  interface DevConfig {
    clientKey: string;
    useMDNS: boolean;
    fallbackHosts: DevHost[];
    inspector: DevInspectorConfig;
  }

  interface DevHost {
    host: string;
    port: number;
  }

  interface DevInspectorConfig {
    enabled: boolean;
    port: number;
  }

  interface DevState {
    enabled: boolean;
    config: DevConfig;
  }
}

interface Strux {
  boot: {
    HideSplash(): Promise<void>;
    Reboot(): Promise<void>;
    Shutdown(): Promise<void>;
  };
  dev: {
    GetConfig(): Promise<StruxRuntime.DevState | null>;
    SetConfig(config: StruxRuntime.DevConfig): Promise<void>;
    SetEnabled(enabled: boolean): Promise<void>;
    Apply(config: StruxRuntime.DevConfig, enabled: boolean): Promise<void>;
    RestartService(): Promise<void>;
    ApplyAndRestart(config: StruxRuntime.DevConfig, enabled: boolean): Promise<void>;
  };
  ipc: {
    /**
     * Register a listener for an event from the Go backend.
     * Returns an unsubscribe function.
     */
    on(event: string, callback: (data: any) => void): () => void;
    /**
     * Remove a previously registered event listener.
     */
    off(event: string, callback: (data: any) => void): void;
    /**
     * Send an event to the Go backend.
     */
    send(event: string, data?: any): void;
  };
}


// Global type declarations
declare global {
  interface App {
    Title: string;
    Counter: number;

    Greet(name: string): Promise<string>;
    Add(x: number, y: number): Promise<number>;
  }

  const App: App;

  const strux: Strux;
  interface Window {
    strux: Strux;
    App: App;
    go: {
      main: {
        App: App;
      }
    }
  }
}

export {};