// Auto-generated Strux Runtime API types
// Generated by: go run ./cmd/gen-runtime-types
// DO NOT EDIT - regenerate with: go run ./cmd/gen-runtime-types -format=ts > src/types/strux-runtime.ts

export const STRUX_RUNTIME_TYPES = `// Strux Runtime API
interface Strux {
  boot: {
    HideSplash(): Promise<void>;
    Reboot(): Promise<void>;
    Shutdown(): Promise<void>;
  };
  ipc: {
    /**
     * Register a listener for an event from the Go backend.
     * Returns an unsubscribe function.
     */
    on(event: string, callback: (data: any) => void): () => void;
    /**
     * Remove a previously registered event listener.
     */
    off(event: string, callback: (data: any) => void): void;
    /**
     * Send an event to the Go backend.
     */
    send(event: string, data?: any): void;
  };
}
`
