// Auto-generated Strux Runtime API types
// Generated by: go run ./cmd/gen-runtime-types
// DO NOT EDIT - regenerate with: go run ./cmd/gen-runtime-types -format=ts > src/types/strux-runtime.ts

export const STRUX_RUNTIME_TYPES = `// Strux Runtime API
declare namespace StruxRuntime {
  interface CapabilityInfo {
    name: string;
    namespace: string;
    description: string;
    supported: boolean;
    provider: string;
    methods: MethodSpec[];
  }

  interface CustomModeSelection {
    width: number;
    height: number;
    refreshMilliHz: number;
  }

  interface DevConfig {
    clientKey: string;
    useMDNS: boolean;
    fallbackHosts: DevHost[];
    inspector: DevInspectorConfig;
    usb: DevUSBConfig;
  }

  interface DevHost {
    host: string;
    port: number;
  }

  interface DevInspectorConfig {
    enabled: boolean;
    port: number;
  }

  interface DevState {
    enabled: boolean;
    config: DevConfig;
  }

  interface DevUSBConfig {
    enabled: boolean;
    subnet: string;
  }

  interface DisplayApplyOptions {
    dryRun: boolean;
  }

  interface DisplayMode {
    widthPx: number;
    heightPx: number;
    refreshHz: number;
    preferred: boolean;
    current: boolean;
  }

  interface DisplayOutput {
    name: string;
    description: string;
    physicalWidthMm: number;
    physicalHeightMm: number;
    enabled: boolean;
    modes: DisplayMode[];
    current: DisplayMode;
    positionX: number;
    positionY: number;
    transform: OutputTransform;
    scale: number;
  }

  interface DisplayOutputChange {
    name: string;
    on: boolean;
    listedMode: ListedModeSelection;
    customMode: CustomModeSelection;
    usePreferred: boolean;
    positionX: number;
    positionY: number;
    scale: number;
    transform: OutputTransform;
  }

  interface ListedModeSelection {
    width: number;
    height: number;
    refreshMilliHz: number;
  }

  interface MethodSpec {
    name: string;
    description: string;
  }

  type OutputTransform = string;
}

interface Strux {
  boot: {
    HideSplash(): Promise<void>;
    Reboot(): Promise<void>;
    Shutdown(): Promise<void>;
  };
  capabilities: {
    List(): Promise<StruxRuntime.CapabilityInfo[]>;
    Supports(name: string): Promise<boolean>;
  };
  dev: {
    GetConfig(): Promise<StruxRuntime.DevState | null>;
    SetConfig(config: StruxRuntime.DevConfig): Promise<void>;
    SetEnabled(enabled: boolean): Promise<void>;
    Apply(config: StruxRuntime.DevConfig, enabled: boolean): Promise<void>;
    RestartService(): Promise<void>;
    ApplyAndRestart(config: StruxRuntime.DevConfig, enabled: boolean): Promise<void>;
  };
  display: {
    List(): Promise<StruxRuntime.DisplayOutput[] | null>;
    Get(name: string): Promise<StruxRuntime.DisplayOutput | null>;
    Apply(changes: StruxRuntime.DisplayOutputChange[], opts: StruxRuntime.DisplayApplyOptions): Promise<void>;
    SetListedMode(output: string, mode: StruxRuntime.ListedModeSelection, opts: StruxRuntime.DisplayApplyOptions): Promise<void>;
    SetCustomMode(output: string, mode: StruxRuntime.CustomModeSelection, opts: StruxRuntime.DisplayApplyOptions): Promise<void>;
    SetPreferredMode(output: string, opts: StruxRuntime.DisplayApplyOptions): Promise<void>;
    SetOutputEnabled(output: string, on: boolean, opts: StruxRuntime.DisplayApplyOptions): Promise<void>;
    SetLayout(output: string, x: number, y: number, opts: StruxRuntime.DisplayApplyOptions): Promise<void>;
    SetScale(output: string, scale: number, opts: StruxRuntime.DisplayApplyOptions): Promise<void>;
    SetTransform(output: string, transform: StruxRuntime.OutputTransform, opts: StruxRuntime.DisplayApplyOptions): Promise<void>;
    GetBacklight(outputName: string): Promise<number | null>;
    SetBacklight(outputName: string, value: number): Promise<void>;
  };
  ipc: {
    /**
     * Register a listener for an event from the Go backend.
     * Returns an unsubscribe function.
     */
    on(event: string, callback: (data: any) => void): () => void;
    /**
     * Remove a previously registered event listener.
     */
    off(event: string, callback: (data: any) => void): void;
    /**
     * Send an event to the Go backend.
     */
    send(event: string, data?: any): void;
  };
}
`;
