// Auto-generated Strux Runtime API types
// Generated by: go run ./cmd/gen-runtime-types
// DO NOT EDIT - regenerate with: go run ./cmd/gen-runtime-types -format=ts > src/types/strux-runtime.ts

export const STRUX_RUNTIME_TYPES = `// Strux Runtime API
interface Strux {
  boot: {
    HideSplash(): Promise<void>;
    Reboot(): Promise<void>;
    Shutdown(): Promise<void>;
  };
}
`
