import { existsSync, readFileSync, unlinkSync } from "fs"
import { isAbsolute, join, relative, resolve, sep } from "path"
import { Settings } from "../settings"

export interface ResolvedBSPRuntimeExtension {
    importPath: string
    sourcePath?: string
}

export const BSP_RUNTIME_IMPORTS_FILENAME = "strux_bsp_runtime_extensions.go"

function toSlashPath(value: string): string {
    return value.split(sep).join("/")
}

function readProjectModulePath(): string | null {
    const goModPath = join(Settings.projectPath, "go.mod")
    if (!existsSync(goModPath)) return null

    const content = readFileSync(goModPath, "utf-8")
    const match = /^module\s+(.+)\s*$/m.exec(content)
    return match?.[1]?.trim() ?? null
}

function resolveFromBSP(value: string): string {
    const bspName = Settings.bspName
    const baseDir = bspName
        ? join(Settings.projectPath, "bsp", bspName)
        : Settings.projectPath

    return isAbsolute(value)
        ? resolve(value)
        : resolve(baseDir, value)
}

function deriveImportPath(sourcePath: string): string {
    const modulePath = readProjectModulePath()
    if (!modulePath) {
        throw new Error("Cannot derive BSP runtime extension import path because go.mod has no module declaration")
    }

    const projectPath = resolve(Settings.projectPath)
    const resolvedSource = resolve(sourcePath)
    const relativePath = relative(projectPath, resolvedSource)

    if (relativePath.startsWith("..") || isAbsolute(relativePath)) {
        throw new Error(`BSP runtime extension path must set import when it is outside the project: ${sourcePath}`)
    }

    return `${modulePath}/${toSlashPath(relativePath)}`
}

export function resolveBSPRuntimeExtensions(): ResolvedBSPRuntimeExtension[] {
    const entries = Settings.bsp?.runtime?.extensions ?? []

    return entries.map((entry) => {
        const sourcePath = entry.path ? resolveFromBSP(entry.path) : undefined
        const importPath = entry.import ?? (sourcePath ? deriveImportPath(sourcePath) : undefined)

        if (!importPath) {
            throw new Error("BSP runtime extension requires an import path")
        }

        return {
            importPath,
            sourcePath,
        }
    })
}

export async function writeBSPRuntimeExtensionImports(): Promise<ResolvedBSPRuntimeExtension[]> {
    const extensions = resolveBSPRuntimeExtensions()
    const outputPath = join(Settings.projectPath, BSP_RUNTIME_IMPORTS_FILENAME)

    if (extensions.length === 0) {
        if (existsSync(outputPath)) {
            unlinkSync(outputPath)
        }
        return extensions
    }

    const imports = extensions
        .map((extension) => `\t_ "${extension.importPath}"`)
        .join("\n")

    const content = `// Code generated by Strux; DO NOT EDIT.

package main

import (
${imports}
)
`

    await Bun.write(outputPath, content)
    return extensions
}

export function getLocalBSPRuntimeExtensionDirs(): string[] {
    return resolveBSPRuntimeExtensions()
        .map((extension) => extension.sourcePath)
        .filter((path): path is string => Boolean(path))
        .filter((path) => existsSync(path))
}

export function getBSPRuntimeImportsPath(): string {
    return join(Settings.projectPath, BSP_RUNTIME_IMPORTS_FILENAME)
}
